// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMSuQ3pIls5cZImSIVEXqJ52i8A1mHaU',
    appId: '1:27831446852:web:3eba08d46f35fad5f57b11',
    messagingSenderId: '27831446852',
    projectId: 'kissan-konnect-71479',
    authDomain: 'kissan-konnect-71479.firebaseapp.com',
    databaseURL: 'https://kissan-konnect-71479-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-konnect-71479.appspot.com',
    measurementId: 'G-FQ2726CNGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbTI2Br1TSUjDaQV5g7TXC3VYUA9cm_A',
    appId: '1:27831446852:android:2a8d219b2aea0169f57b11',
    messagingSenderId: '27831446852',
    projectId: 'kissan-konnect-71479',
    databaseURL: 'https://kissan-konnect-71479-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-konnect-71479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXUzHuZHmEiFNecgPC60WZCvR5uF8jC8E',
    appId: '1:27831446852:ios:20b3f80ff5c72030f57b11',
    messagingSenderId: '27831446852',
    projectId: 'kissan-konnect-71479',
    databaseURL: 'https://kissan-konnect-71479-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-konnect-71479.appspot.com',
    iosClientId: '27831446852-jlc8be41dkvdamuibi88dn4s1rmemlr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kissanKonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXUzHuZHmEiFNecgPC60WZCvR5uF8jC8E',
    appId: '1:27831446852:ios:20b3f80ff5c72030f57b11',
    messagingSenderId: '27831446852',
    projectId: 'kissan-konnect-71479',
    databaseURL: 'https://kissan-konnect-71479-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-konnect-71479.appspot.com',
    iosClientId: '27831446852-jlc8be41dkvdamuibi88dn4s1rmemlr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kissanKonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMSuQ3pIls5cZImSIVEXqJ52i8A1mHaU',
    appId: '1:27831446852:web:9c74ac9297b71321f57b11',
    messagingSenderId: '27831446852',
    projectId: 'kissan-konnect-71479',
    authDomain: 'kissan-konnect-71479.firebaseapp.com',
    databaseURL: 'https://kissan-konnect-71479-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-konnect-71479.appspot.com',
    measurementId: 'G-ZKWFCRVL7K',
  );
}
